### PR TITLE
Kernel patch dlm: keep listening connection alive with sctp mode

### PR DESCRIPTION
**Pull request by feldsam**
#142

Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by msmith626** [comment]
Yes, perfect, thank you! I'll keep this on my machine and merge into 0.1.x later this week (or when I get some other changes for that branch).

Buildbot should have the new image up in about an hour or so.


--Marc

**Comment by feldsam** [comment]
Hi, new image doesn't appear yet, would you check for it? Thanks.

**Comment by msmith626** [comment]
Its there now... a transient error caused the Buildbot to fail earlier.

--Marc

**Comment by feldsam** [comment]
Thank you, I installed yet and look like patch is working :)

**Comment by msmith626** [comment]
Good deal!

On Sat, Aug 29, 2015 at 10:02 PM, Kristian Feldsam <notifications@github.com

**Pull request merged**
