### PR TITLE
Issue 152

### PR DESCRIPTION
**Pull request by dswartz**
Unfortunately, I forgot to remove the original commit message from this PR.  The one which should remain is the one referring to /etc/rc.d/rc.nrpe.  Thanks!

### CODE REVIEW

**Comment by msmith626** [comment]
The problem with this is, the files in /etc/rc.d/ are not editable by the user... well they are, but changes aren't persistent across reboots. It would be better to implement a system like the *BSD's use, and make it so /etc/rc.conf is used for extra daemon configurations. So, basically, each script should source /etc/rc.conf and look for their own variable for extra settings. At least that's how I picture it in my head, but maybe there is a better way to implement it?


--Marc

**Comment by dswartz** [comment]
On 2015-09-20 15:30, Marc A. Smith wrote:
> The problem with this is, the files in /etc/rc.d/ are not editable by
> the user... well they are, but changes aren't persistent across
> reboots. It would be better to implement a system like the *BSD's use,
> and make it so /etc/rc.conf is used for extra daemon configurations.
> So, basically, each script should source /etc/rc.conf and look for
> their own variable for extra settings. At least that's how I picture
> it in my head, but maybe there is a better way to implement it?

Dang.  I assumed being in /etc they could be :(  Let me take another go 
at this then...

**Comment by dswartz** [comment]
On 2015-09-20 15:30, Marc A. Smith wrote:
> The problem with this is, the files in /etc/rc.d/ are not editable by
> the user... well they are, but changes aren't persistent across
> reboots. It would be better to implement a system like the *BSD's use,
> and make it so /etc/rc.conf is used for extra daemon configurations.
> So, basically, each script should source /etc/rc.conf and look for
> their own variable for extra settings. At least that's how I picture
> it in my head, but maybe there is a better way to implement it?

How about the model some linux distros use where daemon foo has a file 
/etc/default/foo that defines these?  Then, presumably, the startup file 
for foo (/etc/rc.d/rc.foo?) does 'source /etc/default/foo' if it exists?

**Comment by dswartz** [comment]
On 2015-09-20 15:30, Marc A. Smith wrote:
> The problem with this is, the files in /etc/rc.d/ are not editable by
> the user... well they are, but changes aren't persistent across
> reboots. It would be better to implement a system like the *BSD's use,
> and make it so /etc/rc.conf is used for extra daemon configurations.
> So, basically, each script should source /etc/rc.conf and look for
> their own variable for extra settings. At least that's how I picture
> it in my head, but maybe there is a better way to implement it?

Of course, my previous suggestion might be more complicated, since it 
involves a new sub-directory, and we would need to make sure that got 
synced as part of the config filesystem...

**Comment by dswartz** [comment]
On 2015-09-20 15:30, Marc A. Smith wrote:
> The problem with this is, the files in /etc/rc.d/ are not editable by
> the user... well they are, but changes aren't persistent across
> reboots. It would be better to implement a system like the *BSD's use,
> and make it so /etc/rc.conf is used for extra daemon configurations.
> So, basically, each script should source /etc/rc.conf and look for
> their own variable for extra settings. At least that's how I picture
> it in my head, but maybe there is a better way to implement it?

The other annoying thing about the /etc/default approach is that that is 
where they indicate whether to run that daemon or not (e.g. something 
like:

# Enable Nagios3 at boottime? ("no" disables nagios3)
# compatibility note: if this variable is _not_ found Nagios3 will start
ENABLED="yes"

... so maybe this isn't a useful solution (it would be *mostly* like the 
existing /etc/default approach in other distros, except for that one 
exception, and if we change to be totally like it, then /etc/rc.conf 
becomes superfluous, which is an incompatible change.  sigh...)

**Comment by msmith626** [comment]
I think the method I suggested would be best, and the most BSD-like. We
simply update the default /etc/rc.conf to be something like this (snipped):
rc.openibd_enable=YES
rc.openibd_options="-x blah -y blah"
rc.opensm_enable=NO
rc.opensm_options="--a 0.0.0.0"
rc.sshd_enable=YES
rc.sshd_options="something else here"

Then in each of the rc scripts (eg, /etc/rc.d/rc.sshd) we source the
/etc/rc.conf file, so:
if [ -f /etc/rc.conf]; then
    source /etc/rc.conf
fi

Then just use the variable, so in the start() functions add
"${rc.sshd_options}" to the command line that calls sshd (for example).

What do you think?


--Marc

**Comment by dswartz** [comment]
On 2015-09-21 10:06, Marc A. Smith wrote:
> I think the method I suggested would be best, and the most BSD-like.
> We
>  simply update the default /etc/rc.conf to be something like this
> (snipped):
>  rc.openibd_enable=YES
>  rc.openibd_options="-x blah -y blah"
>  rc.opensm_enable=NO
>  rc.opensm_options="--a 0.0.0.0"
>  rc.sshd_enable=YES
>  rc.sshd_options="something else here"
> 
>  Then in each of the rc scripts (eg, /etc/rc.d/rc.sshd) we source the
>  /etc/rc.conf file, so:
>  if [ -f /etc/rc.conf]; then
>  source /etc/rc.conf
>  fi
> 
>  Then just use the variable, so in the start() functions add
>  "${rc.sshd_options}" to the command line that calls sshd (for
> example).
> 
>  What do you think?

Sounds good.  I'll give it a shot...

**Comment by msmith626** [comment]
And maybe move any current options that are passed to the binary programs
(daemons) into /etc/rc.conf as well, this way the user has full control if
they want to change the behavior of any rc scripts.

**Comment by dswartz** [comment]
On 2015-09-21 10:17, Marc A. Smith wrote:
> And maybe move any current options that are passed to the binary
> programs
>  (daemons) into /etc/rc.conf as well, this way the user has full
> control if
>  they want to change the behavior of any rc scripts.

Agreed...

**Comment by dswartz** [comment]
Oops, problem here.  '.' is not a legal shell variable name.  The syntax 
you use in rc.conf like rc.nrpe_enable works because rc.common uses 
egrep and cut to slice out the part it wants.  I can do the same with:

[root@esos-test etc]# egrep rc.nrpe_options /etc/rc.conf|cut -d. -f2
nrpe_options="-d -n"

this generates exactly what i want, but the source command apparently 
requires an actual filename.  i guess i could do something like this:

tempname=/tmp/rc.$$
egrep rc.nrpe_options /etc/rc.conf|cut -d. -f2 > ${tempname}
source ${tempname}
rm -f ${tempname}

but that seems kind of icky :(

**Comment by dswartz** [comment]
and yeah, i thought of removing the 'rc.' from the option variable but 
that seems even uglier (e.g. having some variables with 'rc.' prefix and 
some without...)

**Comment by msmith626** [comment]
Hey Dan,

Checking to see if you already got some work done on this? If not, I can
knock it out tomorrow. I will also do the ZFS update in master too. Let me
know.


--Marc

**Comment by dswartz** [comment]
No, I got stuck on this.  Wasn't sure how to proceed and keep in the model you have....

**Comment by msmith626** [comment]
This has been implemented as dde411a59b8444b74ed325bf8a4151e0f13e8fc4.

--Marc

**Pull request closed without merging**
