### PR TITLE
Fixed rc.d dlm script stop action

### PR DESCRIPTION
**Pull request by feldsam**
Added missing umout

Signed-off-by: Kristián Feldsam <feldsam@gmail.com>

### CODE REVIEW

**Comment by msmith626** [comment]
It was quite a while that I worked with this, and I believe I left the
unmount out intentionally... looking at dlm-4.0.1/init/dlm.init I see it
too doesn't unmount it. I assume you've tested it already with unmounting?
It doesn't hang or anything? Is there any downside to leaving it mounted?


--Marc

**Comment by feldsam** [comment]
Hi, ok, so start method should check if is already mounted, because mount throws error.

**Comment by feldsam** [comment]
I removed unmount and added  > /dev/null 2>&1 after mount like in original dlm init script.

**Comment by msmith626** [comment]
Perfect, thank you!

--Marc

**Pull request merged**
